// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-C1RVds8MRHWpJDbz_VRQ6Ie49HWkCk',
    appId: '1:150911091241:web:65551e80972e41a755d238',
    messagingSenderId: '150911091241',
    projectId: 'newsletter-c2d6f',
    authDomain: 'newsletter-c2d6f.firebaseapp.com',
    storageBucket: 'newsletter-c2d6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtFuCbUEQ46zMiP5LvgJzyRt-xZr22Go0',
    appId: '1:150911091241:android:9343be771d4d681355d238',
    messagingSenderId: '150911091241',
    projectId: 'newsletter-c2d6f',
    storageBucket: 'newsletter-c2d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAF5b6ETH7HmmBifjtTCQ2tqeRmXj-WhA',
    appId: '1:150911091241:ios:80a19a00d68523f855d238',
    messagingSenderId: '150911091241',
    projectId: 'newsletter-c2d6f',
    storageBucket: 'newsletter-c2d6f.appspot.com',
    iosBundleId: 'com.example.newsletter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAF5b6ETH7HmmBifjtTCQ2tqeRmXj-WhA',
    appId: '1:150911091241:ios:80a19a00d68523f855d238',
    messagingSenderId: '150911091241',
    projectId: 'newsletter-c2d6f',
    storageBucket: 'newsletter-c2d6f.appspot.com',
    iosBundleId: 'com.example.newsletter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-C1RVds8MRHWpJDbz_VRQ6Ie49HWkCk',
    appId: '1:150911091241:web:df604fc7f023bed855d238',
    messagingSenderId: '150911091241',
    projectId: 'newsletter-c2d6f',
    authDomain: 'newsletter-c2d6f.firebaseapp.com',
    storageBucket: 'newsletter-c2d6f.appspot.com',
  );
}
